### ISSUE TITLE
Passing variable to auth_jwt_key does not work

### ISSUE THREAD

**Issue by remnin** [TeslaGov/ngx-http-auth-jwt-module#60]
I'm trying to combine two parts to make the JWT key:
set $key "${firstPart}SecoundPart";
auth_jwt_key $key;

Not too sure if its the module that needs to interpolation the ${variable}, or the module is not able to use the referanse to $key. Or perhaps I completely missed something else.

Scenario:: I need ${firstPart} to actually be the regex'ed out part/folder(in binHex) of the url, and combine it with a secret key to use nginx to verify if client with JWT can access files in a folder. As then backend can generate JWT (with expiration of 1day) for that folder, thus giving front-end access to all needed files, without having to check complex user->group->project->file auth every time.

Thanks for making a great module!

**Comment by remnin** [comment]
Hey @fitzyjoe ,
I'm trying to use the hex key version, but with a dynamic key.

auth_jwt_key "123DEF"  ----> works

location ~ /filefolder/(?<hexId>[^\/]+)/  {
    auth_jwt_key "${hexId}123DEF"   ----> fails
  OR    set $key "${hexId}123DEF";    auth_jwt_key $key;  ----> fails

As then testing my JWT's validity(signature + exp), can be used for direct file access control in nginx.

**Comment by atomsnc** [comment]
Using a variable won't work. `auth_jwt_key` option is set at nginx configuration stage. An nginx variable is evaluated at runtime.
To make this work, `auth_jwt_key` needs to be a complex value so that at runtime it can be evaluated.

AFAIK, fastest way is to convert `auth_jwt_key` to use `ngx_http_set_complex_value_slot` in `ngx_http_auth_jwt_commands` and use something like following in the handler funtion
```
ngx_str_t  res;

if (ngx_http_complex_value(r, &cv, &res) != NGX_OK) {
    return NGX_ERROR;
}
```
where
r = request
cv = complex value pointer stored in config
res = evaluated string

Also, `auth_jwt_key` type will be changed to `ngx_http_complex_value_t` pointer.

**Comment by remnin** [comment]
Great, thank you!

**Comment by farzadam** [comment]
hi @atomsnc and @remnin   can you help me understand what you did here? I have the same problem but did't understand your solution. can you elaborate on that? I am somehow new to the nginx though

**Comment by atomsnc** [comment]
Hello @farzadam ,

You can read up more on complex values here. (http://nginx.org/en/docs/dev/development_guide.html#http_complex_values)
