### ISSUE TITLE
Can we please have a release if code changes ?

### ISSUE THREAD

**Issue by venomone** [TeslaGov/ngx-http-auth-jwt-module#73]
Would be awesome if any time that there are changes at the code, a new release build gets triggered.

**Comment by JoshMcCullough** [comment]
Hi @venomone Is it binaries you're looking for, or just release information? 

We do create a release tag, etc. ([latest is 1.1.0](https://github.com/TeslaGov/ngx-http-auth-jwt-module/releases/tag/1.1.0) -- sorry, I forgot to create it last week). 

We do not currently publish binaries because we'd have to do it for multiple versions of NGINX and honestly haven't put in the time to automate this. We'd want to include the current version going back to 1.16.x.

If you're looking for a pre-built Docker image, @KensingtonTech has created and [published an image](https://hub.docker.com/r/kensingtontech/nginx-jwt). We hope to make an "official" one from this repo in the future as well.

**Comment by JoshMcCullough** [comment]
Closing as the OP hasn't responded back.

**Comment by JoshMcCullough** [comment]
@venomone we've started publishing binaries when we release a new version. [See v2.0.0](https://github.com/TeslaGov/ngx-http-auth-jwt-module/releases/tag/2.0.0), for example.
