### ISSUE TITLE
Additional JWT algorithm support

### ISSUE THREAD

**Issue by wSedlacek** [TeslaGov/ngx-http-auth-jwt-module#77]
It would be great to support additional algorithms as changing them out in production can be difficult if you have a lot of consumers of the public keys.

Specifically supporting the ones from this list: HS384, HS512, RS384, RS512, ES256, ES384 and ES512

**Comment by JoshMcCullough** [comment]
In the PR linked above, I assed support for the other HS* and RS* algorithms. I didn't add ES* support as we don't currently support any of those algorithms so that might be a bit more work. If ES* support is truly important, please feel free to open another ticket and we'll take a look in the future (or welcome a PR for it).

**Comment by JoshMcCullough** [comment]
@wSedlacek the PR's been merged, so you can now use the higher-bit HS* and RS* alhorithms.
